name: petmatch
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  freezed_annotation: ^2.4.1
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  google_fonts: ^6.2.1
  supabase_flutter: ^2.0.0
  flutter_riverpod: ^2.6.1
  go_router: ^14.6.3
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  uuid: ^4.3.3

  # Location Dependencies:
  philippines_rpcmb: ^0.0.3

  # Designing Dependencies:
  toastification: ^2.3.0
  loading_animation_widget: ^1.3.0
  lottie: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  freezed: ^2.4.6
  json_serializable: ^6.7.1

dependency_overrides:
  app_links: 6.3.0

flutter:
  uses-material-design: true

  assets:
    - .env

    # Logo
    - assets/petmatch_logo.png

    # Get Started Screen
    - assets/get_started_screen/dog.png
    - assets/get_started_screen/paws.png

    # User Profiling
    - assets/user_profile/activities_faces/
    - assets/user_profile/patience_faces/
    - assets/user_profile/affection_faces/
    - assets/user_profile/grooming_faces/
    - assets/user_profile/pet_preference/
    - assets/user_profile/size_preference/

    # Lottie Files
    - assets/lottie/

    # Icons
    - assets/icons/
